build_requires: {}
conflicts: {}
dist_name: .\AltiLog2pcap.exe
distribution_type: par
dynamic_config: 0
generated_by: 'PAR::Packer version 1.043'
license: unknown
par:
  clean: 0
  signature: ''
  verbatim: 0
  version: 1.014
